import re
from typing import Literal, TypedDict


Gender = Literal["male", "female", "unknown"]


class GenderPrediction(TypedDict):
    gender: Gender
    confidence: float
    reason: str


FEMALE_NAMES = {
    "nəzrin",
    "leyla",
    "aysel",
    "günel",
    "nərgiz",
    "fidan",
    "nigar",
    "sevinc",
    "aytən",
    "lamiyə",
    "lamiya",
    "aygün",
    "şəbnəm",
    "xədicə",
    "fatimə",
    "zəhra",
    "nərmin",
    "turanə",
    "turana",
    "ilhamə",
    "fərqanə",
    "mərziyə",
    "aydan",
    "təranə",
    "gülər",
    "sevil",
    "məleykə",
    "samirə",
    "xatın",
    "mədinə",
    "səbinə",
    "əfsanə",
    "rəna",
    "günay",
    "ləman",
    "aytac",
    "aynur",
    "zeynəb",
    "könül",
    "röya",
    "ülviyyə",
    "əminə",
    "ofeliya",
    "şəfəq",
    "şərqiyyə",
    "lalə",
    "bənövşə",
    "firuzə",
    "pərvanə",
    "dilara",
    "elmira",
    "gülnar",
    "humay",
    "iradə",
    "mehriban",
    "nəzakət",
    "rəsmiyyə",
    "səidə",
    "tahirə",
    "vüsalə",
    "yegənə",
    "zamirə",
    "maya",
    "tamilla",
    "svetlana",
    "natavan",
    "zülfiyyə",
    "həcər",
    "salatın",
    "mehri",
    "nərminə",
    "sevdagül",
    "aylin",
    "damla",
    "yağmur",
    "dəniz",
    "şəlalə",
    "sürəyya",
    "balaca",
    "gülxanım",
    "durru",
}

MALE_NAMES = {
    "tural",
    "əli",
    "eli",
    "elvin",
    "nicat",
    "vüsal",
    "vusal",
    "kənan",
    "kenan",
    "murad",
    "orxan",
    "orhan",
    "elşən",
    "elsen",
    "fərid",
    "ferid",
    "kamran",
    "rəşad",
    "resad",
    "şəhriyar",
    "ilqar",
    "bəxtiyar",
    "elnur",
    "mahir",
    "rəşid",
    "anar",
    "vüqar",
    "fuad",
    "zaur",
    "sənan",
    "senan",
    "cavid",
    "eyvaz",
    "rauf",
    "teymur",
    "rəsul",
    "eldar",
    "yunis",
    "yusif",
    "samir",
    "vəli",
    "məmməd",
    "rüstəm",
    "elçin",
    "şahin",
    "ramin",
    "famil",
    "asif",
    "vasif",
    "aqşin",
    "cahangir",
    "bayram",
    "məqsəd",
    "mirzə",
    "emin",
    "nurlan",
    "rəhim",
    "həsən",
    "hüseyn",
    "ibrahim",
    "ömər",
    "osman",
    "süleyman",
    "ismayıl",
    "cabbar",
    "toğrul",
    "ayxan",
    "əsgər",
    "bahadur",
    "ceyhun",
    "elmir",
    "faiq",
    "xəyyam",
    "namiq",
    "pərviz",
    "rövşən",
    "sabir",
    "tariyel",
    "yaşar",
    "ömer",
    "hamid",
    "həmid",
    "şamil",
    "ilham",
    "mübariz",
    "pənah",
}

# Extra Azerbaijani given-name pools sourced from researched Azerbaijani name lists.
ADDITIONAL_MALE_NAMES = {
    "adil",
    "adnan",
    "afiq",
    "afil",
    "ağa",
    "ağahadi",
    "ağaxan",
    "ağamalı",
    "ağamusa",
    "ağasəfa",
    "akif",
    "aqil",
    "allahverdi",
    "anar",
    "arif",
    "asif",
    "asəf",
    "asiman",
    "aslan",
    "atabala",
    "atamoğlan",
    "aydın",
    "azad",
    "azər",
    "baba",
    "bahadır",
    "bayram",
    "behbud",
    "bəhlul",
    "bəhram",
    "bəhruz",
    "bəkir",
    "bəşir",
    "bilal",
    "cabbar",
    "cahangir",
    "cavad",
    "cavid",
    "ceyhun",
    "cəlal",
    "cəlil",
    "cəmil",
    "coşqun",
    "cümşüd",
    "çingiz",
    "dadaş",
    "dilavər",
    "dönməz",
    "dünyamalı",
    "elvin",
    "elariz",
    "elçin",
    "eldar",
    "eldəniz",
    "elgün",
    "elman",
    "elmir",
    "elmidar",
    "elmar",
    "elməddin",
    "elnur",
    "elton",
    "elturan",
    "elsevər",
    "elxan",
    "elşən",
    "elşad",
    "emin",
    "emil",
    "etibar",
    "etiqad",
    "eyyub",
    "əbdül",
    "əflatun",
    "əhməd",
    "əhliman",
    "əhəd",
    "əkbər",
    "ələkbər",
    "ələsgər",
    "əli",
    "əliəkrəm",
    "əliş",
    "əmin",
    "əmir",
    "ənvər",
    "əkrəm",
    "ərtoğrul",
    "əsgər",
    "əşrəf",
    "əyyub",
    "əjdər",
    "faiq",
    "famil",
    "fazil",
    "fariz",
    "fərhad",
    "fərid",
    "fərda",
    "fərman",
    "fəxri",
    "fəxrəddin",
    "fəyyaz",
    "fərrux",
    "fərahim",
    "fikrət",
    "firudin",
    "firdovsi",
    "fəhmin",
    "fəzail",
    "fuad",
    "füzuli",
    "gəray",
    "gülağa",
    "gülbala",
    "gündüz",
    "habil",
    "hafiz",
    "hakim",
    "hacıbəy",
    "heydər",
    "həci",
    "həmid",
    "həsən",
    "həsənağa",
    "həzi",
    "hilal",
    "hümbət",
    "hüseyn",
    "hüseynqulu",
    "ibiş",
    "ibrahim",
    "ilham",
    "ilkin",
    "ilqar",
    "ilyas",
    "imam",
    "imran",
    "inqilab",
    "intiqam",
    "isa",
    "isgəndər",
    "islam",
    "ismayıl",
    "israfil",
    "ixtiyar",
    "kamal",
    "kamil",
    "kamran",
    "kazım",
    "kəmaləddin",
    "kənan",
    "kərim",
    "kəramət",
    "lazım",
    "lətif",
    "mahir",
    "mahmud",
    "maqsud",
    "manaf",
    "mehdi",
    "mehdiqulu",
    "mehman",
    "məhəmməd",
    "məhərrəm",
    "məmməd",
    "mənsur",
    "mikayıl",
    "mirəli",
    "mirzə",
    "musa",
    "murad",
    "muxtar",
    "mübariz",
    "mümtaz",
    "müntəzir",
    "mürsəl",
    "müslüm",
    "müzəffər",
    "nadir",
    "nağı",
    "namiq",
    "natiq",
    "nazim",
    "nazir",
    "nakif",
    "nəcəf",
    "nəriman",
    "nəsib",
    "nəsimi",
    "nicat",
    "nihad",
    "niyaz",
    "niyazi",
    "novruz",
    "nurşən",
    "nurlan",
    "nuru",
    "nurulla",
    "nurşərəf",
}

ADDITIONAL_FEMALE_NAMES = {
    "adilə",
    "afaq",
    "afət",
    "ağca",
    "aidə",
    "akifə",
    "aliyə",
    "almaz",
    "arifə",
    "asilə",
    "aybəniz",
    "ayan",
    "ayçiçək",
    "aygül",
    "ayla",
    "aynurə",
    "aysu",
    "aytəkin",
    "balaxanım",
    "brilyant",
    "cahan",
    "ceyran",
    "ceyhunə",
    "ceyla",
    "cəmalə",
    "cəmilə",
    "çimnaz",
    "çinarə",
    "çiçək",
    "dilarə",
    "dilşad",
    "dünya",
    "durna",
    "dürdanə",
    "dürnisə",
    "elnarə",
    "elnurə",
    "esmira",
    "əcəbnaz",
    "ədibə",
    "əntiqə",
    "əsmər",
    "familə",
    "fatihə",
    "fatma",
    "fəridə",
    "fəxriyyə",
    "firəngiz",
    "fizzə",
    "flora",
    "gülarə",
    "gülay",
    "güllər",
    "gülçöhrə",
    "gülçin",
    "gülnarə",
    "gülnaz",
    "gülnur",
    "gülmira",
    "gültac",
    "gülşən",
    "gülsüm",
    "gültəkin",
    "gülüstan",
    "gülüş",
    "gülxar",
    "gülzar",
    "hicran",
    "hökümə",
    "hüsniyyə",
    "ilkanə",
    "ilqarə",
    "ilnarə",
    "ilahə",
    "inarə",
    "inayət",
    "intizar",
    "jalə",
    "kamilə",
    "kəmalə",
    "kifayət",
    "kövsər",
    "laləzar",
    "leyli",
    "lətifə",
    "lətafət",
    "lütfiyyə",
    "mahirə",
    "mahizər",
    "maisə",
    "mehbarə",
    "mehin",
    "meyransa",
    "məhru",
    "məlahət",
    "mənsurə",
    "məryəm",
    "mərziyyə",
    "məsmə",
    "mətanət",
    "minurə",
    "müşkünaz",
    "mülayim",
    "nahidə",
    "narıngül",
    "naibə",
    "nailə",
    "nanə",
    "natella",
    "natəvan",
    "nazilə",
    "nazimə",
    "nazlı",
    "nəfisə",
    "nisə",
    "növrəstə",
    "nurlana",
    "nuranə",
    "nübar",
    "nüşabə",
    "pakizə",
    "pərvinə",
    "pəri",
    "pərişan",
    "qaratel",
    "qənirə",
    "qızbəs",
    "qönçə",
    "qumru",
    "raifə",
    "ramilə",
    "rasimə",
    "raziyə",
    "reyhan",
    "reyhanə",
    "rəfiqə",
    "rəhilə",
    "rəmziyyə",
    "rəqsanə",
    "rəxşəndə",
    "roza",
    "rövşanə",
    "röyal",
    "röyalə",
    "ruhəngiz",
    "ruhiyyə",
    "ruqiyyə",
    "ruxsarə",
    "rübeyda",
    "rübabə",
    "sabirə",
    "sacidə",
    "sahibə",
    "sayalı",
    "sara",
    "selcan",
    "seyran",
    "səadət",
    "səbirə",
    "sədaqət",
    "səfurə",
    "səhər",
    "səlimə",
    "səmayə",
    "səma",
    "sənubər",
    "səriyyə",
    "sidiqə",
    "sima",
    "simuzər",
    "sitarə",
    "solmaz",
    "sona",
    "suğra",
    "südabə",
    "şahnaz",
    "şeyda",
    "şəfa",
    "şəfiqə",
    "şəhrəbanu",
    "şəmsiyyə",
    "şəhla",
    "şərafət",
    "şükufə",
    "şövkət",
    "tamara",
    "tamaşa",
    "təhminə",
    "tovuz",
    "tomris",
    "turan",
    "tutu",
    "tükəzban",
    "tünzalə",
    "türkan",
    "türkanə",
    "aydan",
    "aygün",
    "aynur",
    "aysel",
}

MALE_NAMES.update(ADDITIONAL_MALE_NAMES)
FEMALE_NAMES.update(ADDITIONAL_FEMALE_NAMES)
MALE_NAMES.difference_update(UNISEX_NAMES)
FEMALE_NAMES.difference_update(UNISEX_NAMES)

UNISEX_NAMES = {
    "nihal",
    "münəvvər",
    "laçın",
    "fimar",
    "arzu",
    "ədalət",
    "edalet",
    "xəyal",
    "xeyal",
    "ümid",
    "umid",
    "dəniz",
    "deniz",
    "ismət",
    "ismet",
    "səfa",
    "sefa",
    "nur",
    "şahmar",
    "bəyan",
    "hikmət",
    "hikmet",
    "şirin",
    "tərlan",
    "terlan",
    "izzət",
    "izzet",
    "şöhrət",
    "soltan",
    "sultan",
    "bəxti",
}

AZ_FEMALE_SURNAME_SUFFIXES = ("ova", "yeva", "eva")
AZ_MALE_SURNAME_SUFFIXES = ("ov", "yev", "ev")
INTERNATIONAL_FEMALE_SUFFIXES = ("skaya", "datter")
INTERNATIONAL_MALE_SUFFIXES = ("ski", "skiy", "son")
NEUTRAL_SUFFIXES = ("zadə", "zade", "lı", "li", "lu", "lü", "soy", "gil")

FEMALE_CONTEXT = (
    re.compile(r"(?iu)\bxanım\b"),
    re.compile(r"(?iu)\b(?:mrs|ms)\.?\s+[A-ZƏÖÜĞÇŞİ]"),
    re.compile(r"(?iu)\bshe\s*/\s*her\b"),
)
MALE_CONTEXT = (
    re.compile(r"(?iu)\bcənab\b"),
    re.compile(r"(?iu)\bmr\.?\s+[A-ZƏÖÜĞÇŞİ]"),
    re.compile(r"(?iu)\bhe\s*/\s*him\b"),
    re.compile(r"(?iu)\bhərbi\s+xidmət\b"),
    re.compile(r"(?iu)\bmilitary\s+service\b"),
    re.compile(r"(?iu)\baskerlik\b"),
    re.compile(r"(?iu)\bвоенная\s+служба\b"),
)


def _prediction(gender: Gender, confidence: float, reason: str) -> GenderPrediction:
    return {"gender": gender, "confidence": confidence, "reason": reason}


def _tokens(full_name: str) -> list[str]:
    return re.findall(r"[^\W\d_]+(?:[-'’][^\W\d_]+)*", full_name.casefold(), flags=re.UNICODE)


def _context_prediction(cv_text: str) -> GenderPrediction | None:
    for pattern in FEMALE_CONTEXT:
        if pattern.search(cv_text):
            return _prediction("female", 0.78, f"CV context matched female indicator: {pattern.pattern}")
    for pattern in MALE_CONTEXT:
        if pattern.search(cv_text):
            return _prediction("male", 0.78, f"CV context matched male indicator: {pattern.pattern}")
    return None


def detect_gender(full_name: str | None, cv_text: str = "") -> GenderPrediction:
    if not full_name or not isinstance(full_name, str):
        return _prediction("unknown", 0.0, "Full name is missing.")

    tokens = _tokens(full_name)
    if not tokens:
        return _prediction("unknown", 0.0, "Full name does not contain usable name tokens.")

    first_name = tokens[0]
    last_name = tokens[-1]

    if "qızı" in tokens or "qizi" in tokens:
        return _prediction("female", 0.99, "Patronymic indicator qızı/qizi matched.")
    if "oğlu" in tokens or "oglu" in tokens:
        return _prediction("male", 0.99, "Patronymic indicator oğlu/oglu matched.")

    # Azerbaijani Russian-origin surname endings are gendered and take
    # priority over an ambiguous first name.
    if last_name.endswith(AZ_FEMALE_SURNAME_SUFFIXES):
        return _prediction("female", 0.98, "Azerbaijani surname ended in -ova/-yeva/-eva.")
    if last_name.endswith(AZ_MALE_SURNAME_SUFFIXES):
        return _prediction("male", 0.98, "Azerbaijani surname ended in -ov/-yev/-ev.")

    # Ambiguous/unisex first names with neutral surnames still require context.
    if first_name in UNISEX_NAMES:
        context = _context_prediction(cv_text)
        return context or _prediction(
            "unknown",
            0.20,
            "First name is ambiguous/unisex and surname/context is not gender-specific.",
        )

    if last_name.endswith(INTERNATIONAL_FEMALE_SUFFIXES):
        return _prediction("female", 0.92, "Surname matched an international female-coded suffix.")
    if last_name.endswith(INTERNATIONAL_MALE_SUFFIXES):
        return _prediction("male", 0.92, "Surname matched an international male-coded suffix.")
    if first_name.endswith("gül"):
        return _prediction("female", 0.90, "First name matched the -gül female indicator.")

    if first_name in FEMALE_NAMES:
        return _prediction("female", 0.92, "First name matched the Azerbaijani/Turkish female-name registry.")
    if first_name in MALE_NAMES:
        return _prediction("male", 0.92, "First name matched the Azerbaijani/Turkish male-name registry.")

    # Explicitly keep neutral surname suffixes from becoming evidence by themselves.
    if last_name.endswith(NEUTRAL_SUFFIXES):
        context = _context_prediction(cv_text)
        return context or _prediction(
            "unknown",
            0.18,
            "Surname suffix is gender-neutral and the first name/context is inconclusive.",
        )

    context = _context_prediction(cv_text)
    if context:
        return context

    return _prediction("unknown", 0.10, "No reliable name or CV context indicator matched.")


def normalize_explicit_gender(value: str | None) -> GenderPrediction:
    normalized = (value or "").strip().casefold()
    male_values = {"male", "m", "man", "kişi", "kisi", "erkek", "мужской", "мужчина"}
    female_values = {"female", "f", "woman", "qadın", "qadin", "kadın", "kadin", "женский", "женщина"}
    if normalized in male_values:
        return _prediction("male", 0.99, "Gender was explicitly stated in the CV.")
    if normalized in female_values:
        return _prediction("female", 0.99, "Gender was explicitly stated in the CV.")
    return _prediction("unknown", 0.25, "Explicit gender text was present but could not be normalized safely.")
